import Foundation
import SwiftUI

#if canImport(FoundationModels)
import FoundationModels
#endif

@Observable
final class PRDGenerationService {
    var isGenerating = false
    var streamedText = ""
    var error: String?

    #if canImport(FoundationModels)
    private var session: LanguageModelSession?
    #endif

    var isAvailable: Bool {
        #if canImport(FoundationModels)
        SystemLanguageModel.default.availability == .available
        #else
        false
        #endif
    }

    @MainActor
    func generate(ingredients: [IngredientData], systemPrompt: String) async {
        isGenerating = true
        streamedText = ""
        error = nil

        #if canImport(FoundationModels)
        guard SystemLanguageModel.default.availability == .available else {
            error = "Foundation Model is not available on this device. Please use a supported device running iOS 26 or later."
            isGenerating = false
            return
        }

        let session = LanguageModelSession(instructions: systemPrompt)
        self.session = session

        let ingredientList = ingredients
            .map { "\($0.emoji) \($0.label) (Category: \($0.categoryId))" }
            .joined(separator: "\n")

        let userPrompt = """
        Generate a PRD for an app with these ingredients:

        \(ingredientList)

        Create a detailed, well-structured Product Requirements Document in Markdown format.
        """

        do {
            let stream = session.streamResponse(to: userPrompt)
            for try await partial in stream {
                streamedText = partial.content
            }
        } catch {
            self.error = "Generation failed: \(error.localizedDescription)"
        }
        #else
        // Simulator fallback: generate a placeholder PRD
        await generatePlaceholder(ingredients: ingredients)
        #endif

        isGenerating = false
    }

    func cancel() {
        #if canImport(FoundationModels)
        session = nil
        #endif
        isGenerating = false
    }

    // MARK: - Simulator Placeholder

    @MainActor
    private func generatePlaceholder(ingredients: [IngredientData]) async {
        let ingredientList = ingredients
            .map { "- \($0.emoji) **\($0.label)**" }
            .joined(separator: "\n")

        let title = ingredients.first?.label ?? "Untitled App"

        let placeholder = """
        # \(title) — Product Requirements Document

        > *Generated by PRD Mixer*

        ## Executive Summary

        This PRD defines a product concept built from the following ingredients. \
        The app combines these elements into a cohesive product vision.

        ## Selected Ingredients

        \(ingredientList)

        ## Problem Statement

        Users need a solution that brings together \(ingredients.map(\.label).joined(separator: ", ")). \
        Existing solutions fail to address this specific combination of needs.

        ## Target Audience

        This app targets users who value the combination of capabilities described by the selected ingredients.

        ## Core Features

        \(ingredients.filter { $0.categoryId == "feature" || $0.categoryId == "appType" }.map { "- \($0.emoji) **\($0.label)**: Core functionality derived from this ingredient." }.joined(separator: "\n"))

        ## Non-Functional Requirements

        - Performance: 60fps UI, sub-2-second generation
        - Privacy: On-device processing where possible
        - Accessibility: Full VoiceOver support, Dynamic Type
        - Offline: Core features work without network

        ## Technical Architecture

        \(ingredients.filter { $0.categoryId == "techStack" || $0.categoryId == "platform" }.map { "- \($0.emoji) **\($0.label)**" }.joined(separator: "\n"))

        ## Milestones

        ### Phase 1 — MVP
        - Core feature implementation
        - Basic UI and navigation

        ### Phase 2 — Enhancement
        - Polish and additional features
        - User feedback integration

        ### Phase 3 — Growth
        - Community features
        - Advanced capabilities

        ---

        *Note: This is a placeholder PRD generated in simulator mode. \
        On a real device with iOS 26+, the Foundation Model will generate a fully detailed PRD.*
        """

        // Simulate streaming by revealing text character by character in chunks
        let characters = Array(placeholder)
        var current = ""
        var i = 0
        while i < characters.count {
            // Advance by a small chunk (roughly one word) to simulate token streaming
            let chunkEnd = min(i + 6, characters.count)
            current += String(characters[i..<chunkEnd])
            streamedText = current
            i = chunkEnd
            try? await Task.sleep(for: .milliseconds(15))
        }
    }
}
